%% 0121: fix tau, 1mp
%% Set path
% global QVDataDir;

filePath = mfilename('fullpath');
[sourceDir, scriptFname, ~] = fileparts(filePath);
[~, projName, ~] = fileparts(sourceDir);

workDir = fullfile('/media/agarg54/Extreme SSD/burst_gt_videos', projName);
resultDir = fullfile(workDir, scriptFname);
mkdir(resultDir);

demosavariaDir = '/media/agarg54/Extreme SSD/code/baselines_apgi/qbp/';
qbm3dBinPath = '/nobackup3/aryan/apgi/baselines/quanta-burst-photography/Matlab/bm3d_matlab_package_4.0.3';
dcrPath = '/p/QuantaBurstPhotography/V1/Real/0111-dark-100khz-1/results0111/dcr.mat';

%% Quanta Parameters
param = struct(...
    ...% These parameters determine which frames are used in align and merge
    'alignTWSize', 7, 'alignTWNum', 11,...
    'mergeTWSize', 7, 'mergeTWNum', 11,...
    'srTWSize', 7, 'srTWNum', 11,...
    'refFrame', 35,...
    ...% Parameters for align and merging, don't change for now
    'numLevels', 4, 'patchSizes', [32 32 32 16],...
    'upsampleRatios', [1 2 2 4], 'searchRadii', [1 1 2 8], 'numLKIters', 3,...
    'imgScale', [],...
    'wienerC', 8,...
    'flowLambda', 0.01,...
    ...% Parameters for sampling
    'maxFlux', 0.7e5, 'tau', 4.17e-5, 'eta', [0.125, 0.135, 0.09], 'dcr', 2, 'sampleSeed', 765,... 
    ...% Parameters for super-resolution, don't change for now
    'srScale', 1, 'combineRadius', 1,...
    'k_detail', [0.3], 'k_denoise', 1, 'D_th', 0.005, 'D_tr', 0.5, 'k_stretch', 1, 'k_shrink', 1,...
    't', 0, 's1', 1, 's2', 12, 'sc', 2, 'M_th', 10,...
    ...% Parameters for post-denoising
    'bm3dSigma', 0.05,...
    'qbm3dBinPath', qbm3dBinPath,...
    'qbm3dSigmaW', 80, 'qbm3dSigmaC', 150,...
    ...% Parameters for correcting hot pixels
    'hpThresh', 100, 'correctDCR', false,...
    'dcrPath', dcrPath,...
    ...% CFA
    'cfa', '',...
    'demosaicBinPath', fullfile(demosavariaDir, 'main'),...
    'cfaFile', fullfile(demosavariaDir, 'bayerBggr_512x512.tif'),...
    ...% Configuration, keep doRefine and deRefineSR false for now
    'dataMatFile', 'dataBayer_0121_1.mat',...
    'doRefine', false, 'doSR', true, 'doRefineSR', false,...
    'computePSNR', true,...
    'debug', true, 'resultDir', resultDir);
param.imgScale = 1./(param.maxFlux * param.tau * param.eta);

param.dataType = 'double'
param.fastMode = false

[cfaImg, cfaMap] = imread(param.cfaFile);
cfa = ind2rgb(cfaImg, cfaMap);

%% Read images
tic;
load(fullfile(workDir, param.dataMatFile), 'imbs', 'imgt', 'dcr', 'dataParam');
%% assert(checkStructFields(param, dataParam));
toc;
fprintf('Finished reading images.\n');

%% Run test script
run ../../TestScripts/scrRgbSrSim_0116